name: Deploy Prd

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 4"

permissions: {}

concurrency:
  group: ${{ github.workflow }}

jobs:
  detect-changes:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      terraform: ${{ steps.changes.outputs.terraform }}
    steps:
      - id: changes
        uses: frasermolyneux/actions/detect-changes@main
        with:
          filters: |
            src:src/**
            terraform:terraform/**

  build-and-test:
    permissions:
      contents: read
    needs: detect-changes
    if: |
      (github.event_name != 'push' || github.ref == 'refs/heads/main') &&
      needs.detect-changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Build static site
        run: npm run build
        working-directory: src

      - name: Remove node_modules before packaging
        run: rm -rf node_modules
        working-directory: src

      - name: Upload site artifact
        uses: actions/upload-artifact@v6
        with:
          name: static-site
          path: src

  terraform-plan-and-apply-dev:
    permissions:
      contents: read
      id-token: write
    environment: Development
    needs: detect-changes
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-dev
    steps:
      - if: needs.detect-changes.outputs.terraform == 'true'
        uses: frasermolyneux/actions/terraform-plan-and-apply@terraform-plan-and-apply/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform != 'true'
        uses: frasermolyneux/actions/terraform-output@terraform-output/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - id: terraform-output
        shell: bash
        run: |
          cd terraform
          echo "static_web_app_name=$(terraform output -raw static_web_app_name)" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true

    outputs:
      static_web_app_name: ${{ steps.terraform-output.outputs.static_web_app_name }}

  static-web-app-deploy-dev:
    permissions:
      contents: read
      id-token: write
    environment: Development
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-dev
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-dev
    if: |
      !failure() && !cancelled() &&
      needs.detect-changes.outputs.src == 'true'
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v7
        with:
          name: static-site
          path: static-site

      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}

      - id: static-web-app-api-key
        uses: azure/CLI@v2
        with:
          inlineScript: |
            static_web_app_api_key=$(az staticwebapp secrets list -n ${{ needs.terraform-plan-and-apply-dev.outputs.static_web_app_name }} -o tsv --query properties.apiKey)
            echo "::add-mask::$static_web_app_api_key"
            echo static_web_app_api_key=$static_web_app_api_key >> $GITHUB_ENV

      - id: deploy-static-web-app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.static_web_app_api_key }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: static-site
          skip_app_build: true

  terraform-plan-and-apply-prd:
    permissions:
      contents: read
      id-token: write
    environment: Production
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-dev
      - static-web-app-deploy-dev
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-prd
    if: |
      !failure() && !cancelled() &&
      needs.terraform-plan-and-apply-dev.result == 'success'
    steps:
      - if: needs.detect-changes.outputs.terraform == 'true'
        uses: frasermolyneux/actions/terraform-plan-and-apply@terraform-plan-and-apply/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform != 'true'
        uses: frasermolyneux/actions/terraform-output@terraform-output/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - id: terraform-output
        shell: bash
        run: |
          cd terraform
          echo "static_web_app_name=$(terraform output -raw static_web_app_name)" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true

    outputs:
      static_web_app_name: ${{ steps.terraform-output.outputs.static_web_app_name }}

  static-web-app-deploy-prd:
    permissions:
      contents: read
      id-token: write
    environment: Production
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-prd
      - static-web-app-deploy-dev
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-prd
    if: |
      !failure() && !cancelled() &&
      needs.terraform-plan-and-apply-prd.result == 'success' &&
      needs.detect-changes.outputs.src == 'true'
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v7
        with:
          name: static-site
          path: static-site

      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}

      - id: static-web-app-api-key
        uses: azure/CLI@v2
        with:
          inlineScript: |
            static_web_app_api_key=$(az staticwebapp secrets list -n ${{ needs.terraform-plan-and-apply-prd.outputs.static_web_app_name }} -o tsv --query properties.apiKey)
            echo "::add-mask::$static_web_app_api_key"
            echo static_web_app_api_key=$static_web_app_api_key >> $GITHUB_ENV

      - id: deploy-static-web-app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.static_web_app_api_key }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: static-site
          skip_app_build: true
